FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.7.7-run

RUN install_packages libbluetooth-dev

WORKDIR /usr/src/

COPY src/* ./

RUN python -m pip install -r requirements.txt

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

CMD ["python3", "-m", "aioblescan"]
