FROM balenalib/%%BALENA_MACHINE_NAME%%

RUN install_packages libbluetooth-dev unzip

RUN install_packages python3 python3-dev python3-pip

WORKDIR /usr/src/

ADD https://github.com/baronbrew/aioblescan/archive/master.zip ./

RUN unzip master.zip && \
    cd aioblescan-master/ && \
    python3 setup.py install && \
    cd -

# CMD ["python3", "-m", "aioblescan", "-T"]
CMD ["/bin/bash"]
