FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.7.7-run

WORKDIR /usr/src/

COPY src/* .

# Enable udevd so that plugged dynamic hardware devices show up in our container.
# ENV UDEV=1

RUN python -m pip install -r requirements.txt

# CMD ["python3", "-m", "aioblescan"]
CMD ["/bin/bash"]
